### ISSUE TITLE
Plugin fails with generic error: "Please make sure there's no syntax error..."

### ISSUE THREAD

**Issue by mehmet-ozgul** [xxpxxxxp/intellij-plugin-golangci-lint#68]
The plugin fails with a generic error `Please make sure there's no syntax error, then check if any config error`. The logs show that the command does not have a file name. When the same command is invoked from the command line with a go file, the command works.

Build version: GoLand 2021.1 Build #GO-211.6693.119 April 6, 2021
Java version: 11.0.10+9-b1341.35x86_64
Operating System: Mac OS X (11.3, x86_64)
JVM version: Dynamic Code Evolution 64-Bit Server VM JetBrains s.r.o.
Go Linter Plugin 1.5.0
```
2021-04-27 10:17:40,106 [ 326654]   WARN -                      go-linter - Run error: level=error msg="Running error: context loading failed: no go files to analyze"
. Please make sure the project has no syntax error. 
2021-04-27 10:17:40,106 [ 326654]   WARN -                      go-linter - Debug command: cd /Users/xxxxx/projects/the_project && export PATH=/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Cellar/go/1.16.3/libexec/bin && export GOPATH= && '/Users/xxxxx/.local/bin/golangci-lint' 'run' '--out-format' 'json' '--allow-parallel-runners' '-j' '4' '--max-issues-per-linter' '0' '--max-same-issues' '0' '--disable-all' '-E' 'exportloopref,funlen,gocritic,goconst,errcheck,gci,sqlclosecheck,dogsled,gocognit,nestif,ineffassign,deadcode,unparam,structcheck,exhaustive,nakedret,prealloc,staticcheck,govet,dupl,gomnd,errorlint,misspell,typecheck,wrapcheck,rowserrcheck,makezero,varcheck,bodyclose,nolintlint,gosec,goerr113,gomodguard,golint,unused,gofmt,unconvert,stylecheck,whitespace,depguard,gosimple,goprintffuncname,gocyclo' '' 
```

**Comment by xxpxxxxp** [comment]
Hi @mehmet-ozgul , Can I have a screenshot of the setting page? That would help me understand the problem, thanks.

**Comment by mehmet-ozgul** [comment]
Here it is, I redacted the golangci-lint executable path and the project path. Both exist and reachable.
![image](https://user-images.githubusercontent.com/68401982/116274766-f4ba3b80-a750-11eb-8df3-e202fc7f7bce.png)

**Comment by xxpxxxxp** [comment]
Thanks, I got it. I guess the problem exists on go files directly under the project root, right? Does sub-folders work fine?

I'll fix it ASAP.

**Comment by mehmet-ozgul** [comment]
Yes, I just verified, go files under subfolders work fine. Thanks!

**Comment by xxpxxxxp** [comment]
Hi @mehmet-ozgul , the problem should be resolved in the latest release, please help to confirm, thanks.

**Comment by Fardinak** [comment]
I was using v1.5.1 and still getting this error. But `golangci-lint` was out of date (v1.39.0) and upgrading it to v1.40.1 seems to have fixed the issue.

**Comment by xxpxxxxp** [comment]
Thanks guys, closing the issue now.
